force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>A date field to specify when to follow up on the application.</description>
    <inlineHelpText>Specifies when to follow up on the application.</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>A text field that can hold a lot of information.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StaleJobApplicationDailyCleanup.cls
/**
 * @description This class checks for stale job application records and closes them
 * @author Jonathan Lyles
 * @created 2025-01-31
 */
public with sharing class StaleJobApplicationDailyCleanup implements Database.Batchable<sObject>, Schedulable{
    /**
     * @description Queues the job
     * @param SchedulableContext context
     */
    public void execute(SchedulableContext context){
        System.enqueueJob(this);
    }
    /**
     * @description Queries for stale jobs
     * @param Database.BatchableContext bc
     * @return Data.QueryLocator A list of stale jobs
     */
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id FROM Job_Application__c WHERE Follow_up_Date__c < N_DAYS_AGO:30 AND (Status__c != \'Closed\' AND Status__c != \'Accepted\')';
        return Database.getQueryLocator(query);
    }
    /**
     * @description Executes the batch job
     * @param Database.BatchableContext bc
     * @param List<Job_Application__c> scope - list of job application records that need to be handled
     */
    public void execute(Database.BatchableContext bc, List<Job_Application__c> scope){
        List<Job_Application__c> jobsToUpdate = new List<Job_Application__c>();
        for(Job_Application__c job : scope){
            job.Status__c = 'Closed';
            job.Notes__c = 'Closed by an automated process';
            jobsToUpdate.add(job);
        }
        update jobsToUpdate;
    }
    /**
     * @description This method executes at the end of the operation.  
     * @param Database.BatchableContext bc
     */
    public void finish(Database.BatchableContext bc){
       //To do: send email to user who called method
    }
}