force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A text or lookup field to store the name of the company where the job application is being sent.</description>
    <inlineHelpText>A text or lookup field to store the name of the company where the job application is being sent.</inlineHelpText>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A long text area to hold detailed information about the job, such as responsibilities, qualifications, benefits, etc.</description>
    <inlineHelpText>Detailed information about the job, such as responsibilities, qualifications, benefits, etc.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text/picklist field to indicate the job location or if it&apos;s remote.</description>
    <inlineHelpText>A text/picklist field to indicate the job location or if it&apos;s remote.</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>A numerical field to capture the expected salary for the job position.</description>
    <inlineHelpText>The expected salary for the job position.</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A text field to keep track of the specific job title or position being applied for.</description>
    <inlineHelpText>The specific job title or position being applied for.</inlineHelpText>
    <label>Position/Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>A URL field to store the web link of the job posting.</description>
    <inlineHelpText>The web link of the job posting.</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/JobApplicationUtils.cls
public with sharing class JobApplicationUtils {
    public static HttpRequest getHttpRequest(){
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://jooble.org/api/03c23409-1a24-4fcf-a10d-d05da812186b');
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            //Define the JSON payload
            String jsonBody = '{"keywords": "Salesforce", "location": "", "salary": 1}';
            request.setBody(jsonBody);
            return request;
    }
    public static List<Object> parseResponse(HttpResponse response){
        System.debug('HttpResponse: ' + response);
        //Parse the JSON string into a Map
        Map<String, Object> parsedResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
        //Get the 'jobs' list from the parsed response
        List<Object> jobs = (List<Object>) parsedResponse.get('jobs');
        System.debug('parsed response: ' + jobs);
        return jobs;
    }
    public static void createJobApplicationRecords(List<Object> jobs){
        //List of job applications that will be added
        List<Job_Application__c> jobApplicationsList = new List<Job_Application__c>();
        //Initialize a counter. Some searches can return thousands of jobs
        Integer count = 0;
        //Iterate over each job, which is an inner map in the 'jobs' list
        for(Object jobObj : jobs){
            if(count >= 5){
                break; //Stop iterating after 5 jobs
            }
            Map<String, Object> job = (Map<String, Object>) jobObj;
            Job_Application__c jobApp = new Job_Application__c();
            jobApp.Name = (String) job.get('title');
            jobApp.Title__c = (String) job.get('title');
            jobApp.Location__c = (String) job.get('location');
            JobApp.Url__c = (String) job.get('link');
            jobApp.Status__c = 'Saved';
            String jobDescription = StringUtils.sanitizeString((String)job.get('snippet'));
            jobApp.description__c = jobDescription.substring(4, jobDescription.length()-4); //removes nbsp which remains at start and end of string
            String salary = (String) job.get('salary');
            if(salary.isNumeric()){
                try{
                    jobApp.salary__c = Decimal.valueOf(salary);
                }catch(Exception e){
                    System.debug(e.getMessage());
                }
            }
            String companyName = (String) job.get('company');
            jobApp.Account__c = AccountUtils.getOrCreateAccount(companyName);
            jobApplicationsList.add(jobApp);
            count++; //increment the counter
        }
        if(!jobApplicationsList.isEmpty()){
            insert jobApplicationsList;
        }
    }
    private static Decimal parseSalary(String salaryAsText){
        List<String> regularExpressions = new List<String>();
        //First pattern example: $109k - $120k
        String regExpression2 = '^\\$([0-9]+)k([\\s]+)-([\\s]+)\\$([0-9]+)k$';
        //Second pattern example: $109k
        String regExpression1 = '^\\$([0-9]+)k';
        //Third pattern example: $50 per hour
        String regExpression3 = 'per\\shour';
        //Fourth pattern example: $50 /hr
        String regExpression4 = '/hr';
        
        List<Pattern> patterns = new List<Pattern>();
        for(String regularExpression : regularExpressions){
            Pattern pattern = Pattern.compile(regularExpression);
            patterns.add(pattern);
        }

        List<Matcher> matchers = new List<Matcher>();
        for(Pattern pattern : patterns){
            Matcher matcher = pattern.matcher(salaryAsText);
            matchers.add(matcher);
        }

        for(Matcher matcher : matchers){
            
        }
        return null;
    }
}