force-app/main/default/objects/Contact/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Contacts (Job Application)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text/picklist field to indicate the job location or if it&apos;s remote.</description>
    <inlineHelpText>A text/picklist field to indicate the job location or if it&apos;s remote.</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>A text field that can hold a lot of information.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StaleJobApplicationDailyCleanupTest.cls
@isTest
private class StaleJobApplicationDailyCleanupTest {
    @testSetup
    static void setupTestData() {
         // Use the TestDataFactory to create test data
         Id profileId = TestDataFactory.getProfileId();
         String uniqueUserName = TestDataFactory.createUniqueUsername();
         User testUser = TestDataFactory.createUser(uniqueUsername, profileId);
         Account testAccount = TestDataFactory.createAccount();
         Contact testContact = TestDataFactory.createContact(testAccount.Id);
         Job_Application__c testJob = TestDataFactory.createJobApplication(testUser.Id, testAccount.Id, testContact.Id, Date.today().addDays(-31));
         Event jobInterview = TestDataFactory.createEvent(testUser.Id, testContact.Id, testJob.Id, testJob.location__c);
    }
    @isTest
    static void StaleJobCleanupTest(){
        Test.startTest();
        StaleJobApplicationDailyCleanup doomedJobs = new StaleJobApplicationDailyCleanup();
        Database.executeBatch(doomedJobs,200);
        Test.stopTest();
        List<Job_Application__c> jobs = [SELECT Status__c, Notes__c FROM Job_Application__c];
        System.assertEquals('Closed', jobs[0].Status__c,'Status should be closed');
        System.assertEquals('Closed by an automated process', jobs[0].Notes__c, 'Notes field should indicate record status changed to closed by an automated process');
    }
}