force-app/main/default/objects/Contact/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Contacts (Job Application)</relationshipLabel>
    <relationshipName>Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Interview.recordType-meta.xml
<RecordType>
    <fullName>Interview</fullName>
    <active>true</active>
    <label>Interview</label>
</RecordType>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A text or lookup field to store the name of the company where the job application is being sent.</description>
    <inlineHelpText>A text or lookup field to store the name of the company where the job application is being sent.</inlineHelpText>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>A date field to specify when to follow up on the application.</description>
    <inlineHelpText>Specifies when to follow up on the application.</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>A text/picklist field to indicate the job location or if it&apos;s remote.</description>
    <inlineHelpText>A text/picklist field to indicate the job location or if it&apos;s remote.</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A Contact related to a job application.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A text field to keep track of the specific job title or position being applied for.</description>
    <inlineHelpText>The specific job title or position being applied for.</inlineHelpText>
    <label>Position/Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class TestDataFactory {

    @isTest
    public static Id getProfileId() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];  
        String profileId = profile.Id; 
        return profileId; 
    }

    public static String createUniqueUsername(){
        String uniqueUsername = 'test' + DateTime.now().getTime() + '@test.com';
        return uniqueUsername;
    }

    public static User createUser(String uniqueUsername, Id profileId){
        User testUser = new User(
            Username = uniqueUsername, 
            Alias = 'test', 
            TimeZoneSidKey = 'America/New_York', 
            LocaleSidKey = 'en_US', 
            ProfileId = profileId, 
            LanguageLocaleKey = 'en_US', 
            EmailEncodingKey = 'UTF-8',
            FirstName = 'test', 
            LastName = 'test', 
            Email = 'test@test.com', 
            isActive = true
        );
        insert testUser;
        return testUser;
    }

    public static Account createAccount(){
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        return testAccount;
    }

    public static Contact createContact(Id accountIdParam){
        Contact testContact = new Contact(FirstName = 'FirstNameTest', LastName = 'LastNameTest', AccountId = accountIdParam);
        insert testContact;
        return testContact;
    }

    public static Job_Application__c createJobApplication(Id ownerIdParam, Id accountIdParam, Id contactIdParam, Date followUpDateParam){
        Job_Application__c testJob = new Job_Application__c(Name = 'JobApplicationName', OwnerId = ownerIdParam ,Title__c = 'TestJobTitle', Account__c = accountIdParam, Location__c = 'TestCity', PrimaryContact__c = contactIdParam, Follow_up_Date__c = followUpDateParam);
        insert testJob;
        return testJob;
    }

    public static Event createEvent(Id ownerIdParam, Id contactIdParam, Id jobApplicationIdParam, String locationParam){
        Date nextBusinessDay = BusinessDayUtils.getNextBusinessDay();
        System.debug(nextBusinessDay);
        Event testInterviewTomorrow = new Event(OwnerId = ownerIdParam, Subject = 'Interview', WhoId = contactIdParam, WhatId = jobApplicationIdParam, Location = locationParam, StartDateTime = DateTime.newInstance(nextBusinessDay, Time.newInstance(9,0,0,0)), EndDateTime = DateTime.newInstance(nextBusinessDay, Time.newInstance(10,0,0,0)));
        insert testInterviewTomorrow;
        return testInterviewTomorrow;
    }
}